좌표받아서 주소로 전환하고 주변 식당 검색
Foundy-LLC/what_should_i_eat pull request #12
Opened 2022-01-08 12:53 UTC by Antonio-990510

geolacator사용해서 좌표얻고
naver API 사용해서 주소로 변환한 뒤 식당 검색
식당 최대 5개 나옴, 식당 개수 더 찾을수 있는 방법 찾아봐야함.

2022-01-09 09:18 UTC, jja08111 commented on lib/services/restaurant_search_api.dart
> +  var myJsonDetail2 = jsonDecode(jsonData)["results"][0]['land']['number2'];
위의 37번째 줄부터 42번째 줄 보면 데이터 받아서 하나하나 디코딩하는데 
이 대신 Json 파싱이 가능하 클래스를 만들어서 클래스 단위로 접근하면 좋을듯

여기 공식 문서가 있음 https://flutter-ko.dev/docs/development/data-and-backend/json

2022-01-11 15:06 UTC, jja08111 requested changes

2022-01-11 15:06 UTC, jja08111 commented on lib/services/restaurant_search_api.dart
> +      address.detail2;
여기를 아래처럼 `Address` 클래스에서 `toString()` 함수를 overriding 해서 구현하면 좋을듯.

```dart
@overriding
String toString() {
  return address.si +
       address.gu +
       address.dong +
       address.detail1 +
       "-" +
       address.detail2;
}
```

2022-01-19 13:11 UTC, jja08111 requested changes
`debugPrint` 호출 너무 많은데 중요한 부분만 남기고 삭제해줘

2022-01-19 13:11 UTC, jja08111 commented on lib/main.dart
> +      home: const SearchTestRestaurantList(),
`LoginPage()`로 변경 해줘 SearchTestRestaurantList는 테스트할때만 사용하면 될듯

2022-01-19 13:11 UTC, jja08111 commented on pubspec.yaml
> +  google_place: ^0.4.3
google 플러그인 사용하는거 아니면 삭제해줘

2022-01-19 13:11 UTC, jja08111 commented on lib/services/restaurant_search_api.dart
> +  //위도와 경도를 나눠서 변수 선언
주석 입력할때 `//` 뒤에 띄어쓰기 해줘 19line처럼

2022-01-19 13:11 UTC, jja08111 commented on lib/services/restaurant_search_api.dart
> +Future<String> fetchData() async {
반환하는게 유저의 위치이니까 함수 이름을 `searchUserLocation` 처럼 변경해줘

2022-01-19 13:11 UTC, jja08111 commented on lib/services/restaurant_search_api.dart
> +Future<dynamic> getRestaurantList(String gusi) async {
함수 이름을 `searchNearbyRestaurant`로 변경해줘
그리고 매개변수이름은 `gusi`보다는 `userLocation`이 좋을듯 아니면 아예 `Address` 객체를 넘기거나  
또한 반환형은 `dynamic`이 아니라 `Future<List<RestaurantModel>>`이 되도록 함수를 만들어야함 

종합하자면 
```dart
Future<List<RestaurantModel>> searchNearbyRestaurant(String userLocation) async {
```

2022-01-19 13:11 UTC, jja08111 commented on lib/services/restaurant_search_api.dart
> +  List<String> foodList = [
이거는 아예 상수로 이용되니까 함수 밖으로 빼서 private 으로 만드는게 나음 만들때 const 붙이고

2022-01-19 13:11 UTC, jja08111 commented on lib/services/restaurant_search_api.dart
> +    //return response.body;
주석 제거

2022-01-19 13:14 UTC, Antonio-990510 commented on lib/main.dart
> +      home: const SearchTestRestaurantList(),
수정완료

2022-01-19 13:16 UTC, Antonio-990510 commented on lib/services/restaurant_search_api.dart
> +Future<String> fetchData() async {
수정완료

2022-01-19 13:20 UTC, Antonio-990510 commented on lib/services/restaurant_search_api.dart
> +Future<dynamic> getRestaurantList(String gusi) async {
수정완료

2022-01-19 13:21 UTC, Antonio-990510 commented on pubspec.yaml
> +  google_place: ^0.4.3
수정완료

2022-01-19 13:22 UTC, Antonio-990510 commented on lib/services/restaurant_search_api.dart
> +  //위도와 경도를 나눠서 변수 선언
수정완료

2022-01-19 13:28 UTC, Antonio-990510 commented on lib/services/restaurant_search_api.dart
> +  List<String> foodList = [
수정완료

2022-01-19 13:29 UTC, jja08111 requested changes

2022-01-19 13:29 UTC, jja08111 commented on lib/services/restaurant_search_api.dart
> +    var rnd = Random().nextInt(45) + 1;
랜덤 max 값에 45를 전달하는데 이것보다는 `foodList.length`를 이용해서 아래와 같이 하는게 좋을듯. 그리고 뒤에 1은 왜 더한거임?
```suggestion
    var rnd = Random().nextInt(foodList.length * 5);
```

2022-01-19 13:41 UTC, jja08111 requested changes

2022-01-19 13:41 UTC, jja08111 commented on lib/services/restaurant_search_api.dart
> +  List<int> selectedRestaurantList = [];
변수이름이 헷갈림 아래처럼 하는게 좋을듯 
```suggestion
  List<int> selectedIndexes = [];
```

2022-01-19 13:57 UTC, Antonio-990510 commented on lib/services/restaurant_search_api.dart
> +    String userLocation) async {
수정 완료

2022-01-19 14:02 UTC, merged